### ISSUE TITLE
Invalid ARN error when setting S3 as storage type

### ISSUE THREAD

**Issue by JingMa87** [drodil/backstage-plugin-qeta#254]
I first set S3 as storage type in `app-config.production.yaml` and add a bucket ARN to the `bucket` property. After deploying the changes and uploading an image in qeta, the image doesn't upload:
![image](https://github.com/user-attachments/assets/4527cea3-ddc8-4287-bea0-d1bb5f4d9698)

In the logs it says the bucket ARN is incorrect, even though it's a correct format:

```
{
  "level": "error",
  "message": "Unhandled rejection Invalid ARN: Unrecognized format: arn:aws:s3:::backstagestack-bucket1234556-abcdefg (type: backstagestack-bucket1234556-abcdefg)",
  "name": "EndpointError",
  "service": "backstage",
  "stack": "EndpointError: Invalid ARN: Unrecognized format: arn:aws:s3:::backstagestack-bucket1234556-abcdefg (type: backstagestack-bucket1234556-abcdefg)\n at evaluateErrorRule (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:471:9)\n at evaluateRules (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:501:7)\n at evaluateTreeRule (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:486:10)\n at evaluateRules (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:503:35)\n at evaluateTreeRule (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:486:10)\n at evaluateRules (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:503:35)\n at evaluateTreeRule (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:486:10)\n at evaluateRules (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:503:35)\n at evaluateTreeRule (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:486:10)\n at evaluateRules (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:503:35)\n at resolveEndpoint (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:532:20)\n at /app/node_modules/@drodil/backstage-plugin-qeta-backend/node_modules/@aws-sdk/client-s3/dist-cjs/endpoint/endpointResolver.js:27:81\n at _EndpointCache.get (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:72:26)\n at defaultEndpointResolver (/app/node_modules/@drodil/backstage-plugin-qeta-backend/node_modules/@aws-sdk/client-s3/dist-cjs/endpoint/endpointResolver.js:27:18)\n at Object.endpointRuleSetHttpAuthSchemeProvider [as httpAuthSchemeProvider] (/app/node_modules/@drodil/backstage-plugin-qeta-backend/node_modules/@aws-sdk/client-s3/dist-cjs/auth/httpAuthSchemeProvider.js:64:26)\n at /app/node_modules/@smithy/core/dist-cjs/index.js:64:26",
  "type": "unhandledRejection"
}
```
To me it seems it's either `@aws-sdk/client-s3/dist-cjs/endpoint/endpointResolver.js` or `@smithy/util-endpoints/dist-cjs/index.js` thats causing the issue. Is there a way around the validation step or to update the dependency to one with a fix?

**Comment by drodil** [comment]
Hi @JingMa87 

Thanks for reporting this. Does @ajuste maybe have some ideas?

**Comment by JingMa87** [comment]
@ajuste Thanks, it's working now. Should I keep this issue open as a bug? Cause changing the documentation to using bucket name instead of ARN should already solve the problem.

**Comment by drodil** [comment]
@JingMa87 I think it should work with both and stripping the arn prefix could be done in the backend. Maybe a small fix for the code would be enough 🤔

**Comment by drodil** [comment]
Additionally, I was thinking of adding LocalStack as part of the local development environment so it's possible to test S3 without actual AWS connection - but that's a topic for another issue

**Comment by veenarm** [comment]
I'm going to do a PR for this, effectively make it strip the arn data if provided in the bucket field.

But also going to modify the connection settings to allow local s3 storage e.g. MinIO and HCP etc.. as they're compatable S3. Effectively mimicking the same as how techdocs do it.
